In [2]:
import scipy.spatial.distance as distance
import numpy as np

In [21]:
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])

In [22]:
distance.cdist(b, a, metric='euclidean')

ValueError: XA must be a 2-dimensional array.

In [5]:
distance.cdist(a[:, np.newaxis], b[:, np.newaxis], metric='euclidean')

array([[  7.,   6.,   1.],
       [  4.,   3.,   4.],
       [  4.,   5.,  12.]])

In [6]:
np.linalg.norm(a, ord=2) - np.linalg.norm(b, ord=2)

1.2955324534752801

In [8]:
distance.cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean')

array([[ 14.2126704]])

In [9]:
a = np.array([0, -1, 11])
b = np.array([3, 7, 2])

In [10]:
a * b

array([ 0, -7, 22])

In [11]:
b.dot(a)

15

In [12]:
np.dot(a, b)

15

In [16]:
a = np.array([8, 10, -1, 0, 0])

In [17]:
a[:, np.newaxis]

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [18]:
a[np.newaxis, :]

array([[ 8, 10, -1,  0,  0]])

In [19]:
a.reshape((5, 1))

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [20]:
a.reshape((1, 5))

array([[ 8, 10, -1,  0,  0]])